// Generated by scripts/harness.py from tests/harness/fleet.json.
window.__FLEET__ = [
  {
    "name": "coot",
    "group": "physical",
    "cores": 32,
    "virt": "none"
  },
  {
    "name": "dove",
    "group": "physical",
    "cores": 32,
    "virt": "none"
  },
  {
    "name": "wader",
    "group": "physical",
    "cores": 24,
    "virt": "none"
  },
  {
    "name": "junco",
    "group": "physical",
    "cores": 2,
    "virt": "none"
  },
  {
    "name": "rail",
    "group": "physical",
    "cores": 2,
    "virt": "none"
  },
  {
    "name": "whitethroat-sp",
    "group": "physical",
    "cores": 4,
    "virt": "none"
  },
  {
    "name": "x1",
    "group": "physical",
    "cores": 4,
    "virt": "none"
  },
  {
    "name": "serin",
    "group": "physical",
    "cores": 8,
    "virt": "none"
  },
  {
    "name": "N1",
    "group": "physical",
    "cores": 16,
    "virt": "none",
    "os": "windows"
  },
  {
    "name": "owl",
    "group": "VM",
    "cores": 16,
    "virt": "wsl",
    "virt_kind": "container"
  },
  {
    "name": "heron",
    "group": "VM",
    "cores": 4,
    "virt": "kvm"
  },
  {
    "name": "falcon",
    "group": "VM",
    "cores": 4,
    "virt": "kvm"
  },
  {
    "name": "roller",
    "group": "VM",
    "cores": 8,
    "virt": "kvm"
  },
  {
    "name": "hawk",
    "group": "VM",
    "cores": 2,
    "virt": "kvm"
  },
  {
    "name": "booby",
    "group": "VM",
    "cores": 2,
    "virt": "kvm"
  },
  {
    "name": "goose",
    "group": "VM",
    "cores": 2,
    "virt": "kvm"
  },
  {
    "name": "thrush",
    "group": "VM",
    "cores": 2,
    "virt": "kvm"
  },
  {
    "name": "towhee",
    "group": "VM",
    "cores": 4,
    "virt": "kvm"
  },
  {
    "name": "eagle",
    "group": "VM",
    "cores": 8,
    "virt": "kvm"
  }
];
