#!/usr/bin/env python3
"""Build (and optionally serve) the browser harness.

The frontend runs standalone against `tests/harness/stub.js`, a fake Tauri
backend. This assembles that into a directory the tests and a browser can use.

**It mirrors the real fleet.** Twice in one session a harness built around five
convenient hosts let a real bug reach the user: a nineteen-host tally is about
70px wider than a five-host one, which was exactly the margin the toolbar had.
`tests/harness/fleet.json` holds the shape — host count, core counts, the
physical/virtual mix, the group names, the Windows host — so what is tested is
what exists.

    python3 scripts/harness.py --serve 8900
    python3 scripts/harness.py --out /tmp/h
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
STUB = ROOT / "tests" / "harness" / "stub.js"
FLEET = ROOT / "tests" / "harness" / "fleet.json"


def build(out: Path) -> Path:
    out.mkdir(parents=True, exist_ok=True)
    # Symlinks, not copies. A copy goes stale: a harness built once keeps
    # being served while src/ moves on, so a test suite can pass against code
    # that no longer exists - worse than no suite, because it reports
    # confidence it has not earned. Linked, every request reads what is on
    # disk now. Only index.html is generated, being the one file that has to
    # be modified.
    for f in list(SRC.iterdir()) + [STUB]:
        if not f.is_file() or f.name == "index.html":
            continue
        link = out / f.name
        if link.is_symlink() or link.exists():
            link.unlink()
        link.symlink_to(f.resolve())

    fleet = json.loads(FLEET.read_text(encoding="utf-8"))
    # Inlined as a global rather than fetched, so the stub stays synchronous
    # and the page has its fleet before the first render.
    (out / "fleet.js").write_text(
        "// Generated by scripts/harness.py from tests/harness/fleet.json.\n"
        f"window.__FLEET__ = {json.dumps(fleet['hosts'], indent=2)};\n",
        encoding="utf-8",
    )

    index = out / "index.html"
    html = (SRC / "index.html").read_text(encoding="utf-8")
    # Before every real script: the stub has to install window.__TAURI__ and
    # the fleet has to exist before app.js runs.
    html = html.replace(
        '<script src="format.js"',
        '<script src="fleet.js" charset="utf-8"></script>\n'
        '<script src="stub.js" charset="utf-8"></script>\n'
        '<script src="format.js"',
        1,
    )
    index.write_text(html, encoding="utf-8")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="", help="where to build (default: a temp dir)")
    ap.add_argument("--serve", type=int, default=0, help="serve on this port")
    a = ap.parse_args()

    out = Path(a.out) if a.out else Path(__file__).resolve().parent.parent / ".harness"
    if out.exists():
        shutil.rmtree(out)
    build(out)
    hosts = len(json.loads(FLEET.read_text(encoding="utf-8"))["hosts"])
    print(f"harness built at {out} ({hosts} hosts)")

    if a.serve:
        import http.server
        import os
        import socketserver

        os.chdir(out)
        socketserver.TCPServer.allow_reuse_address = True
        with socketserver.TCPServer(("127.0.0.1", a.serve),
                                    http.server.SimpleHTTPRequestHandler) as srv:
            print(f"serving on http://127.0.0.1:{a.serve}/index.html")
            srv.serve_forever()
    return 0


if __name__ == "__main__":
    sys.exit(main())
